spring:
  config:
    import: application-secret.yml

mybatis:
  mapper-locations:
    - classpath:/mappers/*.xml
    - classpath:/mappers/*/*.xml

logging:
  level:
    org.springframework.messaging.simp.stomp: DEBUG
    org.springframework.web.socket: DEBUG
